linters:
  disable-all: true
  enable:
    - goimports
    - golint
    - govet
    - deadcode
    - unused
#    - errcheck
linters-settings:
  govet:
    check-shadowing: false
issues:
  exclude-use-default: false